# Generated by Django 3.2.18 on 2023-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('alt_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='postmodel',
            name='images',
            field=models.ManyToManyField(related_name='post', to='blog_api.ImageModel'),
        ),
    ]
