# Generated by Django 3.2.18 on 2023-02-28 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_postmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-published',)},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
